libs/seiscomp/math/filter/butterworth.cpp
libs/seiscomp/math/filter/butterworth.h
libs/seiscomp/math/filter/butterworth.ipp

Replacement of Butterworth IIR filter design routines, thanks to @gempa-jabe for helpful input

[filter] Butterworth filters overhaul; added bandstop

---

libs/seiscomp/math/filter/butterworth.cpp

This PR fixes a subtle bug that effectively turned a ButterworthHighLowpass into a ButterworthLowpass.

[filter] fixes a bug that affected ButterworthHighLowpass

---

plugins/database/sqlite/sqlitedatabaseinterface.cpp

**Features and Changes**:
- Support [SQLite in-memory DB](https://sqlite.org/inmemorydb.html) (using the DB URL `sqlite3://:memory:`)

Support SQLite in-memory DB

---

libs/seiscomp/datamodel/publicobjectcache.cpp
libs/seiscomp/datamodel/publicobjectcache.h

**Features and Changes**:
- Allow specialized implementations to access private members

Provide member accessors

---

libs/seiscomp/io/recordstream/descriptions/global_recordstream.rst

Documentation for https://github.com/SeisComP/common/pull/45

Add documentation to routing RecordStream

---

libs/seiscomp/client/application.cpp
libs/seiscomp/client/configdb.cpp
libs/seiscomp/client/configdb.h

[client] Reset config at app shutdown

---

apps/descriptions/global.xml
libs/seiscomp/processing/operator/ncomps.h
libs/seiscomp/processing/secondarypicker/CMakeLists.txt
libs/seiscomp/processing/secondarypicker/S_aic.cpp
libs/seiscomp/processing/secondarypicker/S_aic.h
libs/seiscomp/processing/secondarypicker/S_v.cpp
libs/seiscomp/processing/secondarypicker/S_v.h

I would like to propose this change that would allow the S-Picker L2 to work on the vertical component. My use case it that I have sensors with a single component only and some other sensors with 3 components, but whose orientation is not known. On both cases the current L2 picker cannot work because it requires 2 horizontal components to compute the L2-norm

[S-L2 picker]: allow to use L2 S picker on vertical component only

---

libs/seiscomp/processing/secondarypicker/S_aic.cpp

Make use of methodID as log message prefix to distinguish between S-L2 and S-V picker. Currently the string "S-AIC" is used, but this is an internal detail that the user is not aware of.

[S picker]: improve log messages

---

apps/config/global.cfg

[core] visualize ttt.homogeneous.tables in scconfig by default

---

libs/3rd-party/locsat/lib/libloc/locate_event.c
libs/seiscomp/seismology/ttt/locsat.cpp

This PR adds the computations of `dtdd` `dtdh` and `takeoff` for `LOCSAT ttt` . Except for `stdloc` there is no code that makes use of these values, but  it is an investment for the future :)
Follow a simple test to verify that all ttt models are consistent. You can see that at close distances `homogeneous`, `LOCSAT` and `libtau` agree, except for super close distances where `LOCSAT` is slightly off due to the low grid density used to generate its tables.  At further distances `libtau` and `LOCSAT` agree and obviously `homogeneus` is totally off.
Unfortunatelly I havent' figured out yet what `dddp` is, so it is not computed.
```
TTT source at lat 0.00 lon 0.00 depth 4.00 Station at 0, 0, 0
libtau      P - vel 5.80 time 0.69 takeoff 179.9 dtdd 0.041 dtdh 0.172 dddp 0.00
LOCSAT      P - vel …
```

[ttt] add computation of dtdd/dtdh/takeoff in LOCSAT

---

libs/3rd-party/locsat/lib/libloc/locate_event.c
libs/seiscomp/seismology/ttt/locsat.cpp

Just a clean-up of my previous commit, no changes in the output of the travel time tables.
I realized I made a silly double conversion of units (rad->km->rad) instead of simply stick with the original value.  And since I was on it, I made general improvements.

[ttt.LOCSAT] code clean-up

---

libs/xml/0.10/sc3ml_0.10__quakeml_1.2.xsl
libs/xml/0.11/sc3ml_0.11__quakeml_1.2.xsl
libs/xml/0.12/sc3ml_0.12__quakeml_1.2.xsl
libs/xml/0.5/sc3ml_0.5__quakeml_1.2.xsl
libs/xml/0.6/sc3ml_0.6__quakeml_1.2.xsl
libs/xml/0.7/sc3ml_0.7__quakeml_1.2.xsl
libs/xml/0.8/sc3ml_0.8__quakeml_1.2.xsl
libs/xml/0.9/sc3ml_0.9__quakeml_1.2.xsl

- Do not export duplicated picks referenced by different amplitudes

[xml] Improve QuakeML XSLT converter

---

libs/seiscomp/io/recordstream/concurrent.cpp

I found out that [Concurrent::next()](https://github.com/SeisComP/common/blob/4422e4418da5266cacb3e471fd6391bae313d898/libs/seiscomp/io/recordstream/concurrent.cpp#L271) can return `nullptr` even if there is still data in the [Concurrent::_queue](https://github.com/SeisComP/common/blob/4422e4418da5266cacb3e471fd6391bae313d898/libs/seiscomp/io/recordstream/concurrent.h#L113) and thus the requested data time window is not fully returned.
When a recordstream thread terminates, [it closes the queue](https://github.com/SeisComP/common/blob/4422e4418da5266cacb3e471fd6391bae313d898/libs/seiscomp/io/recordstream/concurrent.cpp#L261) and that forces the next call to [_queue.pop()](https://github.com/SeisComP/common/blob/4422e4418da5266cacb3e471fd6391bae313d898/libs/seiscomp/io/recordstream/concurre …

[io] Fix concurrent recordstream termination when data still available

---

plugins/locator/stdloc/descriptions/global_stdloc.xml
plugins/locator/stdloc/stdloc.cpp

Just a couple of minor changes that do not affect the code behaviour.

[stdloc] fix config documentation and debug logs

---

libs/seiscomp/processing/magnitudes/MLc.cpp

The current implementation considers the origin depth as the vertical distance to the receiver, which is an assumption that breaks at local scale. The fix computes the vertical distance as the difference between sensor elevation and origin depth.

[MLc] fix computation for distanceMode = 'hypocentral'

---

plugins/locator/stdloc/stdloc.cpp
plugins/locator/stdloc/stdloc.h

This PR fixes #103. Since I was testing the code  I also added a minor improvement (see commit messages).

[stdloc] bug fix and improvement

---

libs/3rd-party/locsat/lib/libloc/locate_event.c
libs/seiscomp/gui/datamodel/originlocatorview.cpp
libs/seiscomp/gui/datamodel/ttdecorator.cpp
libs/seiscomp/io/gfarchive/sc3gf1d.cpp
libs/seiscomp/processing/amplitudeprocessor.cpp
libs/seiscomp/seismology/locator/fixed-hypocenter.cpp
libs/seiscomp/seismology/ttt.cpp
libs/seiscomp/seismology/ttt.h
libs/seiscomp/seismology/ttt/homogeneous.cpp
libs/seiscomp/seismology/ttt/libtau.h
libs/seiscomp/seismology/ttt/locsat.cpp
libs/seiscomp/seismology/ttt/locsat.h
plugins/locator/stdloc/stdloc.cpp

This is the general idea I had in mind for the issue #109. At the moment it doesn't seem a huge performance improvement, but I am thinking at future TTT types that i would like to add.

[ttt] update api w.r.t. issue #109 

---

libs/seiscomp/gui/datamodel/pickerview.cpp

Added a few useful informations to the pick tooltip: publicID, time, comments (if there are any)

[picker] Included in pick tooltip: publicID, time

---

plugins/locator/stdloc/stdloc.cpp
plugins/locator/stdloc/stdloc.h

[stdloc] some improvements

---

plugins/locator/stdloc/stdloc.cpp

@gempa-jabe one last commit to add to the last week series of fixes. I tested `stdloc` at regional scale, comparing the SED `NonLinLoc` and `LOCSAT` solutions to the ones from `stdloc` (in Octree and least-square modes) and, except for this PR bug,  I found the solutions to be consistent between locators. 
That said I do not believe there  is good reason to use `stdloc` over `NonLinLoc` and `LOCSAT`, since they are perfectly fine, but I like the workflow of `scanloc`+`stdloc` because a user can choose the velocity model of their choice and the processing adapts to it. 
Eventually I would like to release a code that enables NLL grids as Seiscomp travel time tables and that would make `scanloc`+`stdloc` workflow interesting at regional scale.

[stdloc] fix octtree search failures in case of very large cell sizes

---

libs/seiscomp/gui/datamodel/eventfilterwidget.ui
libs/seiscomp/gui/datamodel/eventlistview.cpp
libs/seiscomp/gui/datamodel/eventlistview.h
libs/seiscomp/gui/datamodel/eventlistview.ui

Added a phase count filter in addition to the existing ones (lat, lon, mag, depth) for the SQL query in scolv. Also added two new check buttons to i) hide final/rejected events and ii) hide new events from the retrieved list.

Adding phase count filter and hide f/x/new events checkbuttons

---

plugins/locator/stdloc/descriptions/global_stdloc.rst
plugins/locator/stdloc/descriptions/global_stdloc.xml

Better explain the use case for each location method and add an example configuration as well.

[stdloc] update documentation

---

libs/3rd-party/leastsquares/lsmr.cpp
libs/3rd-party/leastsquares/lsmr.h
libs/3rd-party/leastsquares/solver.h
plugins/locator/stdloc/stdloc.cpp

This PR should allow `stdloc` in `LeastSquares` mode to better detect unstable solutions that would end up with crazy uncertainties as reported by @gempa-dirk.

[stdloc] detect and reject unstable solutions (LeastSquares)

---

libs/seiscomp/datamodel/exchange/quakeml.cpp

Added missing `preferredPlane` attribute

[datamodel] Bugfix in quakeml.cpp

---

libs/seiscomp/gui/datamodel/pickerview.cpp
libs/seiscomp/gui/datamodel/pickerview.h
libs/seiscomp/gui/datamodel/pickerview.ui

This PR is about to help with issue #164. It has been opened to play with various implementations and to discuss them more closely to the code rather than in issues.

[gui] Make waveform amplitude values audible
