SeisComP/common

libs/seiscomp/math/filter/stalta.cpp
libs/seiscomp/math/filter/stalta.h
libs/swig/math.i

This is a cleanup of the STALTA filters. Changes include:
* General cleanups and improved readability
* Improved behavior at the beginning of a segment, with the initialization time reduced to the length of the STA window. This has turned out to be enough and also robust.
* Addition of a non-recursive STALTA_Classic class.
* Updated math.i to generate the proper Python wrappers.

[filtering] STALTA cleanups

---

libs/seiscomp/processing/waveformprocessor.cpp

This PR fixes two minor issues regarding gap interpolation:
- Correctly return whether gap was handled
- Compare `_gapThreshold` with sampling interval; the minimum allowed gap threshold is twice the sampling interval

Fix gap interpolation

---

libs/seiscomp/processing/waveformprocessor.cpp

If I'm not completely mistaken, there is an issue when saving the last sample after filling (filtering) the data. Instead,
the raw sample before filling needs to be saved. This is required since gaps are handled before data is filled.

Save last sample before filling values

---

libs/seiscomp/math/filter/abs.h
libs/seiscomp/math/filter/average.cpp
libs/seiscomp/math/filter/average.h
libs/seiscomp/math/filter/biquad.h
libs/seiscomp/math/filter/butterworth.h
libs/seiscomp/math/filter/chainfilter.h
libs/seiscomp/math/filter/const.h
libs/seiscomp/math/filter/cutoff.cpp
libs/seiscomp/math/filter/cutoff.h
libs/seiscomp/math/filter/iirdifferentiate.cpp
libs/seiscomp/math/filter/iirdifferentiate.h
libs/seiscomp/math/filter/iirintegrate.cpp
libs/seiscomp/math/filter/iirintegrate.h
libs/seiscomp/math/filter/minmax.cpp
libs/seiscomp/math/filter/minmax.h
libs/seiscomp/math/filter/op2filter.h
libs/seiscomp/math/filter/rmhp.cpp
libs/seiscomp/math/filter/rmhp.h
libs/seiscomp/math/filter/seismometers.cpp
libs/seiscomp/math/filter/seismometers.h
libs/seiscomp/math/filter/stalta.h
libs/seiscomp/math/filter/taper.cpp
libs/seiscomp/math/filter/taper.h

**Features and Changes**:
- Consistently reset the filter state when (re)configuring the sampling frequency. (Otherwise, calling `Seiscomp::Processing::WaveformProcessor::initFilter()` in `Seiscomp::Processing::WaveformProcessor::setupStream()` may leave filters with state in case of changing sampling frequencies.)
- Consistently apply SeisComP coding conventions with regards to virtual member functions and overrides.
Please review carefully.

Consistently reset filters

---

libs/seiscomp/gui/datamodel/originlocatorview.cpp

As discussed in https://forum.seiscomp.de/t/scv4-scolv-focal-sphere-quadrants-colours , the colour of the unconfirmed focal sphere compression quadrants is a bit confusing. Keeping the same kind of colour than original, there are 3 other possibilities:  « Dark », « Mid » and « Midlight » (see attached). I propose to use « Mid ». 
I understand the colour for the quadrants after being confirmed is « Highlight » with a 25% blend with background color, which is good, and I don't intend to propose any change on that.

scolv/ focal sphere/ quadrants colours : darker?

---

libs/seiscomp/core/recordsequence.h

This PR adds a convenience method that returns the TimeWindow the TimeWindowBuffer is constructed with. Currently there is no way to know that TimeWindow. In my code I have to keep a separate data structure just to access that information. Thanks for your review.

Allow TimeWindowBuffer to return its TimeWindow

---

libs/seiscomp/processing/timewindowprocessor.cpp

**Changes**:
- Only accept margins >= 0
- Also sync the `_safetyTimeWindow` member

Sync safety time window

---

libs/seiscomp/io/recordstream/descriptions/global_recordstream.rst

I have just configured a `routing` RecordStream and I found it tricky to get the syntax right. Sot I would like to add an additional example in the documentation, so that users can  simply replace the server names and archives path with their own settings

Add further configuration example for `routing` RecordStream

---

libs/seiscomp/seismology/magnitudes.h

The default radiation pattern was 1.0 but should have been 0.52 according to Tsuboi et al. (1995). This is fixed in this PR.

Mwp bugfix

---

libs/seiscomp/io/exporter.cpp
libs/swig/io.i
libs/swig/io_python_wrap.cxx

Change ExportSink.write(unicode, length) to ExportSink.write(bytes) to fix unicode XML.

[exporter] Fix broken unicode XML

---

libs/seiscomp/gui/datamodel/amplitudeview.cpp
libs/seiscomp/gui/datamodel/pickerview.cpp

This is related to issue #66 
The code forces same depth of libtau 0.01 km. That is for consistency

[GUI] allow theoretical arrivals with negative depth in picker/amplitude guis

---

apps/descriptions/global.xml
libs/seiscomp/seismology/ttt/CMakeLists.txt
libs/seiscomp/seismology/ttt/descriptions/global_homogeneous.xml
libs/seiscomp/seismology/ttt/homogeneous.cpp

Dear developers,
this is a proposal to add a new travel time table for a homogeneous velocity model. This is clearly a niche use case, but since I needed it I thought to share the code and make it available to other users. This is also useful for certain testing cases, for example when developing new modules or for generating unit testing code.
If you are interested in merging this PR you might be want to review the interface name, currently `homogeneous` and how the model name is currently used ("abused") to pass the constant P and S velocity to the model. This is clearly an abuse of the model name, but it is very convenient for the user.
Currently it looks like the following:
Luca

[core]: add TTT for a homogeneous velocity model

---

libs/xml/0.10/sc3ml_0.10__quakeml_1.2.xsl
libs/xml/0.11/sc3ml_0.11__quakeml_1.2.xsl
libs/xml/0.12/sc3ml_0.12__quakeml_1.2.xsl
libs/xml/0.5/sc3ml_0.5__quakeml_1.2.xsl
libs/xml/0.6/sc3ml_0.6__quakeml_1.2.xsl
libs/xml/0.7/sc3ml_0.7__quakeml_1.2.xsl
libs/xml/0.8/sc3ml_0.8__quakeml_1.2.xsl
libs/xml/0.9/sc3ml_0.9__quakeml_1.2.xsl

SCML documents describing large earthquakes were taking a long time to convert to QuakeML, with almost all that time being spent in the loop that outputs picks that aren't referenced by amplitudes. (For example, an event with ~600 arrivals in its preferred origin was taking 12 seconds.)
By precomputing the list of referenced amplitudes once per origin (rather than computing it on the fly for each pick), performance is greatly improved (down to 400ms in my 600-arrival example).
I've got another PR open touching the same files (#72), but I figured I'd keep this separate because it doesn't change the output.

[xml] Improve performance in scml to quakeml XSLT

---

libs/seiscomp/datamodel/utils.cpp

In the special case of the component dip being -90° or +90° the component azimuth is undefined, unneeded and sometimes not set. This patch prevents such a stream from being ignored or processed incorrectly if the azimuth is not set.

Patch of getThreeComponents()

---

libs/seiscomp/seismology/ttt/homogeneous.cpp

In my previous implementation of the homogeneous ttt I didn't compute the partial derivatives because I used LOCSAT as the reference implementation, which doesn't compute them.
However I then realized that they are required if someone wants to write a locator so here is a PR that adds the missing computation.
I verified them with the values returned by libtau and they look correct.  In the tests I used source locations close to the station so that there is no reflection/refraction involved.
```
* TTT source at lat 0.05 lon 0.00 depth 1.00 Station at 0, 0, 0(ele)
libtau P      - time 0.97 takeoff 98.0 dtdd 18.981 dtdh 0.024 dddp 0.00
homogeneous P - time 0.97 takeoff 100.2 dtdd 18.858 dtdh 0.031 dddp 0.00
libtau S      - time 1.67 takeoff 99.4 dtdd 32.648 dtdh 0.048 dddp 0.00
homogeneous S …
```

[ttt] add computation of dtdd/dtdh in homogeneous

---

libs/seiscomp/io/recordstream/sdsarchive.cpp

The SDSArchive::close() leaves the class in an inconsistent class state and the next call to SDSArchive::next() crashes.
I noticed this behaviour when using `sdsarchive` within a `routing` record stream. The debugger showed the following:

[sdsarchive] crash if used within a concurrent RS

---

libs/seiscomp/processing/amplitudeprocessor.cpp
libs/seiscomp/processing/amplitudeprocessor.h
libs/seiscomp/processing/amplitudes/CMakeLists.txt
libs/seiscomp/processing/amplitudes/iaspei.cpp
libs/seiscomp/processing/amplitudes/iaspei.h
libs/seiscomp/processing/amplitudes/m_B.cpp
libs/seiscomp/processing/amplitudes/m_B.h
libs/seiscomp/processing/amplitudes/mb.cpp
libs/seiscomp/processing/amplitudes/mb.h

This PR implements the computation of mb according to the IASPEI Magnitude WG recommendations. There are some differences in the technique for determining the relevant extrema in the waveforms but the most notable difference is the correction by the WWSSN-SP amplitude response. This correction was not done previously and will have some effect especially for events for which the WWSSN-SP filtered P waveforms have a dominant period of more than one second. We will then observe on average a slight mb _increase_. For shorter periods mb will slightly _decrease_.
This is currently off by default and can be enabled by setting `amplitudes.iaspei = true` in the config. I am open to enable it by default, though.
Thanks to Jens Havskov for triggering this!
Note that this PR also implements a not …

Compute mb magnitude according to the IASPEI Magnitude WG recommendations

---

libs/seiscomp/io/recordstream/file.cpp
libs/seiscomp/io/recordstream/file.h

File::addStream now supports * ? () |
This is related to https://github.com/SeisComP/main/pull/59 - without wildcards support that PR is of limited use.

[io] add support for wildcards in File RecordStream

---

libs/3rd-party/leastsquares/solver.h
plugins/locator/stdloc/descriptions/global_stdloc.rst
plugins/locator/stdloc/descriptions/global_stdloc.xml
plugins/locator/stdloc/stdloc.cpp
plugins/locator/stdloc/stdloc.h

This PR completes all the features I wanted to add to the locator. I will focus on bug fixing now. Not that I am aware of any bugs, but it's a young software so the bugs are there for sure. I am currently using the locator on two projects so I am actively looking at the results and hopefully I should find out if there are major issues.
Anyhow, here is the list of changes:
- add `OctTree` and `OctTree+LeastSquares` as optional methods.
- remove `IgnoreInitialLocation` capability from the locator. This is because the initial location either is not used (`GridSearch` and `OctTree` search) or is mandatory (`LeastSquare`). So it doesn't make sense to make it optional in `scolv`.
- add `FixedDepth` capability. This is certainly useful is several cases.
- Remove `GridSearch.maxRms` …

[stdloc] add OctTree method

---

libs/seiscomp/logging/common.h

Calling a macro with such a common word (expect) easily results in code breakage. The macro is not even useful (it might have been useful in the past).
I would suggest to completely remove the macro.

[logging] avoid declaration of 'expect' macro

---

libs/seiscomp/datamodel/exchange/quakeml.cpp

When using obspy.client to retrieve data there is a user warning for each arrival. The arrivals in quakeml-format do not have a valid publicID.
UserWarning: 'smi:org.gfz-potsdam.de/geofon/smi:local/LED/pick/6b98ba97-c5b1-4488-ae7c-29752b40e0fb_smi_local/LED/c4c35d6d-cd06-4596-bcd8-0956f155c935' is not a valid QuakeML URI. It will be in the final file but note that the file will not be a valid QuakeML file.

[quakeml] fix invalid ResourceUri

---

libs/seiscomp/seismology/locator/eigv.cpp

This bug affects `LOCSAT` and `StdLoc`.
I noticed this infinite loop because `StdLoc` enables the confidence ellipsoid by default (LOCSAT has it disabled). Since I am working on  playbacks with tens of thousands of events the bug became apparent.
I don't know why they implemented the original code in that way, but they must have had a good reason. So I am not super happy to change the implementation, but the possible infinite loop is way too problematic. I'll let you decide what to do.
Here is a naive test for the changed code, in case you want to play around with it:
```
#include <iostream>
#include <cmath>
using namespace std;
/*
* Code copied from common/libs/seiscomp/seismology/locator/eigv.cpp
*/
double r8_max ( double x, double y )
{
double value;
if ( y < x )
{
value = x;
}
else
{ …
```

[locator] fix possible infinite loop in locator uncertainty computation

---

libs/seiscomp/math/geo.cpp
libs/seiscomp/math/geo.h

This is a small improvements for the next API revision. This PR allows to pass null arguments to `Seiscomp::Math::Geo::delazi`: either one of `dist`, `azi` or `baz` can be omitted.
That would make the code nicer in many places and it will also save some computations: the trigonometric functions can be expensive and sometimes are called millions of times.

[core] allow null arguments to Seiscomp::Math::Geo::delazi

---

libs/seiscomp/seismology/ttt/homogeneous.cpp
libs/seiscomp/seismology/ttt/libtau.cpp
plugins/locator/stdloc/stdloc.cpp

Small performance improvements when using `stdloc` with `homogeneous`

[trunk] take advantage of the new Math::Geo::delazi api

---

apps/messaging/scmaster/config/scmaster.py

Fix cases like:
<pre>
* setup kernel
* setup scmaster
+ Running MySQL database setup script
/home/sysop/seiscomp/share/db/mysql_setup.py
/bin/sh: -c: line 0: syntax error near unexpected token `)'
/bin/sh: -c: line 0: `/home/sysop/seiscomp/share/db/mysql_setup.py seiscomp
sysop sysop sysop sysop localhost the_)password False
/home/sysop/seiscomp/share/db' 
</pre>

[setup] Fix an issue with special characters in db password, etc.

---

libs/seiscomp/datamodel/utils.cpp

The orientation of three sensor components is supposed to be mutually perpendicular, but this is not always achieved (particularly the separate STS-1 horizontal components). We therefore tolerate up to 5 degrees of deviation from perfect perpendicularity. This includes all deviations from perpendicularity that can be found at least in the global networks.

Be a little more tolerant in handling non-perpendicular sensor components

---

libs/seiscomp/math/filter/CMakeLists.txt
libs/seiscomp/math/filter/bpenv.cpp
libs/seiscomp/math/filter/bpenv.h

Band pass and envelope filter
This is a recursive band pass and envelope filter combination. Strictly speaking the envelope would require frequency-domain filtering because it requires the Hilbert transform of the signal. We cannot compute the _exact_ Hilbert transform using time-domain recursive filters. By applying a rather narrow band pass to the data, however, we can compute an _approximate_ Hilbert transform. This is because for a narrow-band signal the Hilbert transform will be the scaled time derivative. This actually works quite well in practice as long as the band pass is not too wide and has relatively steep corners to block energy from outside the pass band. A band width of one octave and a filter order of four was found to work well in most cases. It is therefore highly …

[filter] Adding recursive envelope filter

---

plugins/locator/stdloc/descriptions/global_stdloc.xml
plugins/locator/stdloc/stdloc.cpp
plugins/locator/stdloc/stdloc.h

Dear @gempa-dirk,
this is an update to the configuration parameters of `stdloc` as discussed by email, plus some minor changes.
1 - `GridSearch.cellSize` has been replaced by `GridSearch.numPoints`
2 - Removed default value of `GridSearch.numPoints` (former `GridSearch.cellSize`) to force the user to make a choice
3 - Removed `GridSearch.autoLatLon` and replaced by the special value `auto` in `GridSearch.center` 
4 - default method is now `LeastSquares` (so that is behaves as `LOCSAT` locator)
5 - added `LeastSquares.depthInit` (like `LOCSAT` locator)
6 - update some parameter descriptions
This is a trivial patch, since I didn't make any change in the math or in the logic of the code. However renaming the parameters can lead to annoying bugs. I tested the code myself, but not as much as I …

[stdloc] revision of configuration parameters and their defaults

---

libs/seiscomp/seismology/ttt/homogeneous.cpp

Currently the homogeneous was reading its parameters exclusively from global.cfg at all three configuration stages. This makes it impossible to configure it per application, e.g. in app.cfg.

[ttt/homogeneous] Try to read application configuration first

---

libs/seiscomp/gui/datamodel/pickerview.cpp

This allows the [pick time confidence level](https://www.seiscomp.de/doc/base/api-python.html#seiscomp.datamodel.TimeQuantity.confidenceLevel) to be shown in the tooltip of the picker window in `scolv`. It is useful with automatic pickers providing confidence level, e.g., based on machine learning.

[gui] Add time confidence to picker marker tooltip

---

plugins/locator/stdloc/descriptions/global_stdloc.xml
plugins/locator/stdloc/stdloc.cpp

Despite my efforts to fix the eigv/chi2 code, I still see random crashes (it happened only one, but I was not able to reproduce it). That library is a nightmare so I do not trust that code very much and I would like to disable the computation of the confidence ellipsoid by default.
The common usage of `stdloc` is to be used by `scanloc` and in this case the confidence ellipsoid is not required.
If that code crashes when called from scolv that is annoying, but the user notices the issue. However, If the code crashes when called by scanloc than who is going to notice that?

[stdloc] set enableConfidenceEllipsoid to false by default

---

libs/seiscomp/gui/datamodel/amplitudeview.cpp
libs/seiscomp/gui/datamodel/pickerview.cpp

Dear developers,
I would like to increase the distance filtering precision  in the `PickerView` and `AmplitudeView`.  Now that we can use  the hypocenter distance in these GUIs I have started paying attention to this detail and the current `SpinBox` precision doesn't allow for decimal points. So, if this doesn't affect other use cases, I would like to allow at least 1 decimal point.
thanks
Luca

[gui] increase distance filtering precision to 1 digital point

---

plugins/locator/stdloc/stdloc.cpp

This is a minor thing, but with the  `OctTree+LeastSquares` method it makes sense to find the `LeastSquares` solution even if the `OctTree`  solution is on the grid boundary, because it is very likely that the user select a coarse grid and the solution most certainly lays on the cell close to the boundary.

[stdloc] disable OctTree grid boundary check if OctTree+LeastSquares

---

plugins/locator/stdloc/stdloc.cpp

The bug is present with LeastSquares and GridAndLsqr methods

[stdloc] confidence elipsoid is not computed when FixedDepth is enabled

---

plugins/locator/stdloc/stdloc.cpp

This PR fixes the error reported by @gempa-dirk via email.
----
However I still believe the parameter `PSTableOnly` needs a discussion( @gempa-jabe & @gempa-dirk).
In my opinion the phase label assigned by the user (e.g. 'Pg', 'Pn' etc) should be passed to the `TravelTimeTable`  implementation without modification when `stdloc` calls `ttt::compute(...)` or `ttt:::computeTime(...)`.
However, in practice, the travel time table (both `LOCSAT` and `libtau`) sometimes disagree  with the phase label assigned by the user. This can happen because the user may know better the local geology than a generic velocity model and so `stdloc` needs to convert the ttt query from a specific phase to a generic `P` or `S` to avoid a failure.  In a different case a user may use TauP Toolkit to properly …

[stdloc] fix phase name detection

---

libs/seiscomp/seismology/ttt/homogeneous.cpp

Use std::out_of_range exception when queried for data outside the user defined model ranges.

[homogeneous] throw out_of_range instead of NoPhaseError
